# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TomeksDEV
email: info@tomeksdev.custom
description: >- # this means to ignore newlines until "baseurl:"
  Meet Tomo (aka Vujca), your tech-savvy problem-solving sidekick from Croatia. Master of networks, defender of firewalls, and lover of all things Linux!
tagline: Building uptime & stories
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomeksdev.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  tomeksdev
default_image: "/assets/img/post/TomeksDEV-blog.png"
company:
  name: "TomeksDEV"
  legal_name: "TomeksDEV"
  url: "https://tomeksdev.com"
  logo: "/assets/img/post/TomeksDEV-blog.png"
  founding_date: "2015-01-01"
  same_as:
    - https://github.com/tomeksdev
    - https://www.linkedin.com/in/tomo-novak-39777ba1
    - https://facebook.com/tomeksdev
keywords:
 - Network Administrator
 - System Administrator
 - Virtualization
 - Firewalls
 - Datacenter
 - Linux
 - Windows
 - Servers
 - Storage

navigation:
  - label: Home
    icon: fa-blog
    url: /
  - label: About
    icon: fa-id-card
    url: /about/
  - label: Projects
    icon: fa-briefcase
    url: /projects/
  - label: Contact
    icon: fa-envelope
    url: /contact/
  - label: GitHub
    icon: fa-github
    icon_style: fab
    url: https://github.com/tomeksdev
    external: true

author:
    name: Tomo Novak (aka Vujca)
    email: info@tomeksdev.com
    facebook: https://facebook.com/vujca
    messenger: https://m.me/tomeksdev

social-network-links:
  email: "info@tomeksdev.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  facebook: https://facebook.com/tomeksdev
  github: https://github.com/tomeksdev
  youtube: https://www.youtube.com/@Tomek4341
  linkedin: https://ie.linkedin.com/in/tomo-novak-39777ba1
  instagram: https://instagram.com/vujca
  telephone: +385996893981
  whatsapp: https://wa.me/996893981
  messenger: https://m.me/vujca

highlighter: rouge
permalink: :year/:month/:day/:title

# Build settings
#theme: TomeksDEV
plugins:
  - jekyll-feed
pagination:
  per_page: 10
  path: "/page/:num/"

category_colors:
  Blogging: "#ff4c4c"
  Server: "#2dd4bf"
  Programming: "#22c55e"
  Testing: "#a855f7"
  Security: "#475569"
  Default: "#ff4c4c"

giscus:
  repo: "tomeksdev/tomeksdev.github.io"
  repo_id: "MDEwOlJlcG9zaXRvcnk3MzU1MTI5OQ=="
  category: "Comments"
  category_id: "DIC_kwDOBGJNw84CzPr-"
  mapping: "og:title"
  input_position: "bottom"
  reactions_enabled: "1"
  emit_metadata: "0"
  strict: "0"
  theme: "preferred_color_scheme"
  lang: "en"

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
